services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Load environment variables from .env file
      - AGORA_APP_ID=${AGORA_APP_ID}
      - AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE}
      - AGORA_CUSTOMER_ID=${AGORA_CUSTOMER_ID}
      - AGORA_CUSTOMER_SECRET=${AGORA_CUSTOMER_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - USE_RESPONSES_API=${USE_RESPONSES_API:-false}
      - AGENT_ID=${AGENT_ID}
      - LANGFLOW_URL=${LANGFLOW_URL}
      - LANGFLOW_API_KEY=${LANGFLOW_API_KEY}
      - LANGFLOW_FLOW_ID=${LANGFLOW_FLOW_ID}
      - LLM_PROVIDER=${LLM_PROVIDER:-langflow}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
